### ISSUE TITLE
not showing in resolume 6

### ISSUE THREAD

**Issue by leolodreamland** [DanielArnett/360-VJ#1]
they're not 64 bit apparently!

**Comment by DanielArnett** [comment]
Interesting, maybe check with the project I forked from.
https://github.com/leadedge/ShaderMaker

**Comment by leolodreamland** [comment]
Actually I found it. It’s in sources not fx. Therefore slightly redundant.

**Comment by DanielArnett** [comment]
Did you get it working?

**Comment by leolodreamland** [comment]
Can’t use as effect. Source only. You get a nice black circle! I’ll file a
report with resolume guys.

**Comment by DanielArnett** [comment]
Hmm I think I've seen this before. Are you using one that you've compiled or one of my releases? A lot of times it will just show up blank whenever an error is thrown. Don't see why a new version of Resolume would have issues with an FFGL plugin.

**Comment by leolodreamland** [comment]
Just using your release.

**Comment by DanielArnett** [comment]
Odd. Mac or PC? Also have you tried all of my plugins to the same result?
Also check out leadedge's ShaderMaker project and maybe try to run some
others on Resolume 6. I wonder if it's an issue with Resolume interacting
with the kind of FFGL plugins that ShaderMaker generates.

**Comment by leolodreamland** [comment]
Mac. Not tried any other shader maker plugs. I did think that.

**Comment by francoestrubia** [comment]
Source only: you need to declare as FF_EFFECT, and this to '1'.
// Input properties allow for no texture or for four textures
	SetMinInputs(0);

Daniel, can you tell me what ID has used on each shader? Is just to compile it with the same one.

**Comment by brendanrbercik** [comment]
Resolume Arena 6 made the switch from 32-bit to 64-bit. All FFGL plugins
need to be re-made 64-bit compatible.

**Comment by DanielArnett** [comment]
@francoestrubia look at my different branches, I have one branch for each effect. Checkout line [~72 in ShaderMaker.cpp](https://github.com/DanielArnett/360-VJ/blob/d50b68d522190c726df44147c5301a7159bf6c86/ShaderMaker.cpp#L72) in each branch for the ID.

Also, what's changing FF_EFFECT do? Do you think it will fix this 64bit issue? I'm getting Resolume Avenue 6 in a few weeks and can update the Releases then.

**Comment by francoestrubia** [comment]
Daniel, sorry. I missed the branches, just looked one cpp and believe you change the shader code and recompile it. I see now.

About declaration as Fx: aside of setting as FF_EFFECT, you need to declare the minimum texture input as 1 [ SetMinInputs(0); ], other case will be appear as a source on resolume 6.

**Comment by francoestrubia** [comment]
I'm not a programmer and believe me, took me 30 seconds to download, change that value and compile on xcode. And is flat2fisheye working on arena 6.

**Comment by DanielArnett** [comment]
Well very cool! I'm upgrading to Avenue 6 so in a week or two I'll test this out, mark this issue as resolved, and update the releases. Thanks for looking into this.

**Comment by leolodreamland** [comment]
Yes!

**Comment by francoestrubia** [comment]
Thanks for the clarification Lynn. 
 I'm just learning, but noticed the scaling issue. I was taking some fragment code from ISF files and porting it to shadertoy, because is the only way I can compile it through your shadermaker (only way to my skills). Code working fine on shadertoy plattform, gets that strange behaviour when used on arena 6. Now I undestand why!
I will take a look at the freeframemaker, looks promising. 👍

**Comment by leadedge** [comment]
Yes this was a strange one to solve. Many thanks to Eric Newman who knew the solution straight away.
The FreeframeMaker project is more general purpose and you have to set up your own uniforms, but then you are not limited to the ShaderToy set. The downside is that this is more time consuming and there is some programming skill required. 
I have devoted more time to ShaderToySender which uses the same resource method and generates plugins directly from the menu without any programming at all.

**Comment by francoestrubia** [comment]
I saw the shadertoysender on the forum looking for some help on shadermaker. Seems to be a fantastic! tool, I need to pickup a win machine.  
The freeframemaker can take more time to learn, but at first look is clearest than shadermaker to that purpose. About that, if I wanna use buffers (as used in trails and delay filters) is this template my best chance?

**Comment by leadedge** [comment]
I have had in mind that you could set up your own set of most commonly used uniform variables instead of the ShaderToy ones. Multiple buffers means a complete re-write. It could be done but I have spent time on other things. Contact me for the latest test version of ShaderToySender.

**Comment by morleyrigged** [comment]
Hey gang, 

So whats the final word, this plugin is lost to the winds due to 64 bit compatibility issues?

**Comment by DanielArnett** [comment]
@morleyrigged no way! Thanks for checking in on this. It looks like these guys have the issue worked out. I just finished a grueling year in grad school and I'm looking forward to playing with Resolume again soon. I'll get the new release out this summer, as soon as next week if things aren't too crazy at work.

**Comment by morleyrigged** [comment]
@DanielArnett Thanks! If you need a beta tester send it on over too me :)

**Comment by brendanrbercik** [comment]
Hi all,

@DanielArnett - is it very time consuming to update the plugin? I would LOVE to run something even just passable (like a beta) this week. I have an installation coming up that could make great use of your plugin!

Anyway, don't want to sound needy or demanding...but if it's on your roadmap and doable, I would be forever grateful and make a financial contribution to the project for your time. Thank you!

**Comment by DanielArnett** [comment]
@francoestrubia did you compile all 4 of the effects for OSX? If so, could you send those to me? Then I can go ahead and publish the OSX version too. Big thanks for solving this by the way. Other than your change I just had to set visual studio to compile for x64.

**Comment by leolodreamland** [comment]
this would rock

**Comment by brendanrbercik** [comment]
Amazing! Daniel, you are a rock star!

**Comment by DanielArnett** [comment]
Pushed the OSX version onto the [release page](https://github.com/DanielArnett/360-VJ/releases).
