### ISSUE TITLE
Fix seams in OSX version

### ISSUE THREAD

**Issue by DanielArnett** [DanielArnett/360-VJ#10]
Fix the seam mentioned by @philipkrueger in Issue https://github.com/DanielArnett/360-VJ/issues/5#issuecomment-1432750006
<img width="662" alt="Bildschirm­foto 2023-02-16 um 09 56 28" src="https://user-images.githubusercontent.com/15050074/219318946-f617e5b7-beed-4f7c-8267-f54e465b338d.png">

Seems to only appear in OSX.

**Comment by DanielArnett** [comment]
@philipkrueger could you send me the source image? Looks useful for debugging/catching little things.

**Comment by philipkrueger** [comment]
Sure
![Mapping-Grid_ER_3_w](https://user-images.githubusercontent.com/15050074/219406693-95966373-ed21-4a5e-9bc7-9166b072a45d.jpg)

**Comment by jorisdejong** [comment]
I think the seam could be caused because the UVs are multiplied by the MaxGLCoords in the vertex shader, but all your math operations in the fragment shader are expecting normalized coordinates

**Comment by jorisdejong** [comment]
Yes. Instead of multiplying by MaxUV in the vertex shader, you can pass through the uvs as they are. Then you multiply by MaxUV in the fragment shader, after you've done all your operations

**Comment by jorisdejong** [comment]
AddSubtract doesn't do any math that expects uvs to be exactly 0...1, like your plugin does. So for AddSubtract, it doesn't matter whether it multiplies at the beginning or at the end

**Comment by DanielArnett** [comment]
Okay [here's the diff](https://github.com/DanielArnett/360-VJ/pull/11/files#diff-1ff3bbbe4dfe1d2e3d77779d5a255e18dbcfd38025c70a7d3c4e06b756560914). @xinaesthete could you pull and build the bugfix/fix-seams branch on OSX, we may have fixed the seam.

**Comment by xinaesthete** [comment]
Hi @DanielArnett I made a new build but for some reason I'm not seeing the plugin in Resolume. Hopefully I'll manage to remember enough about how this all works and check it soon.

**Comment by xinaesthete** [comment]
Ah, just seen you replied - it somehow fixed itself although I'm really not sure how. I did update Resolume.

[Reprojection.bundle.zip](https://github.com/DanielArnett/360-VJ/files/11114195/Reprojection.bundle.zip)

Haven't tested very thoroughly; I didn't see seams of the kind mentioned here I don't think, but I do see discrepancies depending on composition resolution.

Composition resolution 5760x2880 (as per the insta360 source):
![ReprojectionHiRes](https://user-images.githubusercontent.com/674834/228917055-f1d3b9c6-b72c-4e55-b3b9-671371d70936.jpg)

1920x1080:
![Reprojection1080p](https://user-images.githubusercontent.com/674834/228917068-f3bc86a4-be7f-4572-b3b3-abf12a973c55.jpg)

Nothing that can't be fixed with a few clicks of the 'maximise video' button AFAICT, but then I've never seen a situation where that didn't fix the kinds of seams we're talking about, either.

**Comment by xinaesthete** [comment]
Seems unlikely that it would be OS specific, I might conceivably try on Windows at some point.

**Comment by xinaesthete** [comment]
I think part of what I was seeing was just that Resolume doesn't necessarily propagate changes to composition resolution to the clip scaling immediately correctly.

However, it does remain the case that the 'maximise video' clip setting is rather important:

https://user-images.githubusercontent.com/674834/228926039-2e18fd5f-ff50-4499-9b14-9367bac1b3d0.mp4

**Comment by xinaesthete** [comment]
So, correct results are gleaned when the equirectangular source is scaled to the composition resolution (which may well be a different aspect ratio, ie 2:1 vs 16:9 in many cases). I think that was already true without the recent changes.

So it seems like your code still prefers for UVs to be stretched 0-1, I haven't looked at the code or this thread in depth.

**Comment by xinaesthete** [comment]
That makes sense, and it starts to make more sense that it could be OS specific... so I don't know if there could be an underlying Resolume/FFGL bug... maybe the `FFGLTextureStruct.Hardware[Width|Height]` aren't set correctly?

**Comment by jorisdejong** [comment]
If that were the case, all my plugins would not work correctly either and I would be up to my ears in support emails. 

You can check if you can recreate the issue by loading the previous version of the plugin and using the test image provided in this thread, in a composition set to the same size.

On my hardware, the 4253x2126 test image gets padded to 4288x2176, which is enough for a seam to be very visible.

**Comment by jorisdejong** [comment]
Awesome, confirmed on my end. The seam is gone, the slightly off axis tilt is gone, and flat to flat also gives the correct output now. That test image is a keeper ;)

**Comment by DanielArnett** [comment]
Yeah I wrote the plugin to either be applied directly to the clip, or to be applied to a clip that is filling up the layer completely. I should probably make that more explicit. From your end do you guys think this looks good for a release?

**Comment by DanielArnett** [comment]
Thank you everyone for your help!

**Comment by philipkrueger** [comment]
Works great, thank you so much for this awesome plugin :)
