### ISSUE TITLE
Resolume 6.1.0 MAC not working, and both of them in the generator list, pleaseeeeee fix it

### ISSUE THREAD

**Issue by spacevj22** [DanielArnett/360-VJ#2]
amazing plugin! please fix it if you have time, it's not working on the latest Resolume os anymore.

Thank you Thank you Thank you 
Thank you Thank you Thank you

best

**Comment by DanielArnett** [comment]
Hey don't think I've forgotten about you, just busy with school. You work in a planetarium? I'd love to learn more about which domes are using this!
