### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by kman1898** [DanielArnett/360-VJ#6]
with resolume 6 360 vj causes persistent feedback. Once you turn off the effect and back on the previous feedback is still there. Really hoping there is a fix to this as it is not this way in resolume 7

**Comment by DanielArnett** [comment]
Are you using the Resolume 6 version of the shader or the 7?

**Comment by kman1898** [comment]
I am using 6. I’m more than happy to show you what I’m talking about if need be

**Comment by DanielArnett** [comment]
I'd recommend deleting the 360vj effect you have installed and download this version to try out. 
https://github.com/DanielArnett/360-VJ/releases/tag/6.0.0
Then restart Resolume.

**Comment by DanielArnett** [comment]
Hmm that's strange. Yeah can you send screenshots or anything?

**Comment by kman1898** [comment]
Sure check these out. I tried what you said and removed 360 vj and downloaded from github. Same issue. 

 https://m.imgur.com/gallery/fmrdoqb

**Comment by DanielArnett** [comment]
Getting a page not found error for that gallery. Have you clicked publish on it? Or just post the photos directly in this thread.

**Comment by kman1898** [comment]
Here you go. Not sure why copying that work. 

https://m.imgur.com/a/fmrdoqb

**Comment by DanielArnett** [comment]
Which plugin are you using? It looks like you're using the "Fisheye to Equi" effect. [If so then this line could be the problem](https://github.com/DanielArnett/360-VJ/blob/master/source/FFGL2/FisheyeToEqui/FisheyeToEqui.cpp#L169). I was trying to give people a way to blend fisheye images, and forgot to take that line out.

**Comment by kman1898** [comment]
I’m using the one called 360 vj. What you just linked me has different plugins though. The ones I just downloaded and replaced were 360 vj, 360 to fisheye, fisheye rotation and flat to fisheye. 

What you just linked has equiRotation, equiToFisheye, fisheye rotation and flat to fisheye. So I guess i will try that

**Comment by DanielArnett** [comment]
Yeah, it's confusing. 360VJ = EquiRotation

**Comment by kman1898** [comment]
I just tried to import equiRotation, equiToFisheye, fisheye rotation and flat to fisheye from the 1.5 binaries and now none of them show in resolume

**Comment by kman1898** [comment]
I went back and downloaded 360 vj for resolume and installed these and it’s showing in resolume but again is having the same feedback issue
![image](https://user-images.githubusercontent.com/60245031/73110420-56e41b00-3ed4-11ea-8eab-54fd26b0e94c.jpg)

**Comment by kman1898** [comment]
The resolume 6 plugins have the old names. The names you’re using are only for 7

**Comment by kman1898** [comment]
Any idea what the problem could be? I’m just hopefully for a non feedback version in resolume 6

**Comment by DanielArnett** [comment]
The clips you're using, do they have alpha? Can you try videos without any
alpha?

**Comment by kman1898** [comment]
Same issue. It happens to every clip on both of my computers as well as all my friends that use 360 vj on resolume 6. It is definitely fixed in 7. Maybe try it on your resolume 6?

**Comment by kman1898** [comment]
@DanielArnett any luck? You see what I’m talking about right?

**Comment by DanielArnett** [comment]
At this point I'm only supporting the latest release of resolume. I did clean up alpha blending though so I'm closing this one.
