### ISSUE TITLE
Sphere2Sphere

### ISSUE THREAD

**Issue by tartavull** [DanielArnett/360-VJ#7]
I'm a bit confused about https://github.com/DanielArnett/360-VJ/blob/master/source/FFGL2/EquiRotation/EquiRotation.h

Is this supposed to go from an equirectangular image to another equirectangular image?

**Comment by DanielArnett** [comment]
Yes, it allows you to change the "center" of an equi image. Kind of like
panning a camera. Here's an example of the effect on an equirectangular map
of the Earth.
https://www.stuff.co.nz/travel/news/109292256/new-zealand-front-and-centre-of-map

**Comment by tartavull** [comment]
Thanks a lot, Daniel -- this code made my day.
One last question before closing the issue. 

I assume "flat" refers to rectilinear as in https://www.ptgui.com/man/projections.html.
Is there a way of going from equirectangular to flat?

**Comment by DanielArnett** [comment]
Yeah flat means rectilinear. What's your project? The easy way would be to
just do EquiToFisheye, then crop the output. That'll make the output look
like a GoPro video- still fisheye but not the full fisheye circle. I have
been meaning to redo this project and have one shader that converts any
projection into any other, but it'll take a lot of effort I don't have
right now. But I do have the shader code already written.

**Comment by tartavull** [comment]
Is that shader code available in some branch? That's exactly what I was trying to do!

**Comment by DanielArnett** [comment]
It's sadly not so easy. I have the shader code, but there's a lot of params
that would need added in. I don't have much time, I'm working on some other
projects now. If you were interested I might be able to put an hour or two
aside and get it started, then give you some instructions to finish it up.
The shader is mostly working and will go between Equi, Flat, Fisheye,
CubeMap, and like one or two others in both directions. All that really
needs done is to hook up the inputs into the massive shader. I could do the
first one, and then show you how to set up the rest.

**Comment by tartavull** [comment]
That sounds like a great plan :)

**Comment by DanielArnett** [comment]
Okay, first step; download this and get it building. Specifically build the
AddSubtract effect.
https://github.com/resolume/ffgl
What build environments do you have? OSX? Visual Studio?

**Comment by DanielArnett** [comment]
This has been addressed by the latest release 8.0.0.
